# Generated by Django 3.0.3 on 2020-02-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfolio',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
