# Generated by Django 3.0.3 on 2020-02-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfolio', '0002_pfolio_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfolio',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
