# Generated by Django 3.0.3 on 2020-03-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfolio', '0004_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.TextField(max_length=1000)),
                ('subject', models.ImageField(upload_to='pfolios')),
                ('message', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
