# Generated by Django 3.0.3 on 2020-03-02 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfolio', '0005_contactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='Contact',
        ),
    ]
